.ds q \N'34'
.TH RENDERCHECK 1 2025-04-26 "rendercheck @version@" "X Version 11"
.SH NAME
rendercheck \- simple tests of the X Render extension.
.SH SYNOPSIS
.nf
\fBrendercheck\fP [\fB\-d\fP|\fB\-\-display\fP \fIdisplay\fP] \
[\fB\-i\fP|\fB\-\-iter\fP] [\fB\-\-sync\fP]
    [\fB\-t\fP|\fB\-\-tests\fP \fItest1\fP,\fItest2\fP,\fItest3\fP,...] \
[\fB\-o\fP|\fB\-\-ops\fP \fIop1\fP,\fIop2\fP,\fIop3\fP,...]
    [\fB\-v|\fB\-\-verbose\fP] [\fB\-\-minimalrendering\fP]

\fBrendercheck\fP [\fB\-\-help\fP|\fB\-\-version\fP]
.fi
.SH DESCRIPTION
.B rendercheck
is a set of simple tests of the X Render extension.
It is designed for authors of Render implementations in X Servers.
.SH OPTIONS
.TP
.BI \-d\fR|\fP\-\-display " display"
Specifies the display to test against.
.TP
.BI \-i\fR|\fP\-\-iter " iterations"
Specifies the number of times to repeat each operation before sampling results.
Some X Servers may behave differently (hardware vs software rendering paths)
depending on the previous operations done,
so this may be used to influence the server's choices.
.TP
.B \-\-sync
Enables synchronous xlib operation, for debugging.
.TP
.BI \-t\fR|\fP\-\-tests " test1,test2,test3..."
Enables only a specific subset of the possible tests.
Test names include
.BR \%fill ", " \%dcoords ", " \%scoords ", "
.BR \%mcoords ", " \%tscoords ", " \%tmcoords ", "
.BR \%blend ", " \%composite ", " \%cacomposite ", "
.BR \%gradients ", "\%repeat ", " \%triangles ", "
and
.BR \%bug7366 .
Names must be separated by commas and have no spaces.
.TP
.BI \-f\fR|\fP\-\-formats " format1,format2,format3..."
Enables only a specific subset of the possible formats.
Only formats listed in the server-supported format list are available.
Names must be separated by commas and have no spaces.
.TP
.BR \-o | \-\-ops
Enables only a specific subset of the Render operators.
.TP
.BR \-v | \-\-verbose
Enables verbose printing of information on tests run,
and successes and failures.
.TP
.B \-\-minimalrendering
Disables copying of offscreen destinations to the window,
which is on by default to provide the user with visual feedback.
.TP
.B \-\-help
Prints usage message and exits.
.TP
.B \-\-version
Prints version information and exits.
.SH BUGS
Several limitations are documented in the TODO file accompanying the source.
Please report any further bugs you find to
.UR https://gitlab.freedesktop.org/xorg/test/rendercheck/-/issues/
the rendercheck issue tracker
.UE .
.SH AUTHORS
Eric Anholt, with help from Keith Packard.
